# Generated by Django 5.1.6 on 2025-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_membership_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('team_approved', 'Team Approved')], default='pending', max_length=20),
        ),
    ]
